from cassandra.cluster import Cluster
from cassandra.auth import PlainTextAuthProvider
import json

# This secure connect bundle is autogenerated when you donwload your SCB, 
# if yours is different update the file name below
cloud_config= {
  'secure_connect_bundle': 'secure-connect-achievers-project.zip'
}

# This token json file is autogenerated when you donwload your token, 
# if yours is different update the file name below
with open("achievers_project-token.json") as f:
    secrets = json.load(f)

CLIENT_ID = secrets["clientId"]
CLIENT_SECRET = secrets["secret"]

auth_provider = PlainTextAuthProvider(CLIENT_ID, CLIENT_SECRET)
cluster = Cluster(cloud=cloud_config, auth_provider=auth_provider)
session = cluster.connect()

# Command to use a keyspace
try:
    query = "use achievers"
    session.execute(query)
    print("Inside the employee_keyspace")
except Exception as err:
    print("Exception Occured while using Keyspace : ",err)

try:
    query = "drop table conversion_event"
    session.execute(query)
    print("Table dropped successfully !!")
except Exception as err:
    print("Exception Occured while dropping the table: ",err)

# Command to create a table inside a KEyspace
try:
    query = """create table conversion_event(
                ad_id int,
                user_id text,
                conversion_timestamp text,
                product_id text,
                revenue decimal,
                campaign text,
                product text,
                target_start_date text,
                target_end_date text,
                age int,
                gender text,
                interests list<text>,
                primary key(ad_id,user_id,conversion_timestamp)
              )
            """
    session.execute(query)
    print("Table created inside the keyspace")
except Exception as err:
    print("Exception Occured while creating the table : ",err)

