from cassandra.cluster import Cluster
from cassandra.auth import PlainTextAuthProvider
import json
import sys

# This secure connect bundle is autogenerated when you donwload your SCB, 
# if yours is different update the file name below
cloud_config= {
  'secure_connect_bundle': "C:/Users/rohit_jcjttq8/Desktop/Data Engineering Bootcamp/HACKATHON/datasource stream/casandra/secure-connect-achievers-project.zip"
}

# This token json file is autogenerated when you donwload your token, 
# if yours is different update the file name below
with open("C:/Users/rohit_jcjttq8/Desktop/Data Engineering Bootcamp/HACKATHON/datasource stream/casandra/achievers_project-token.json") as f:
    secrets = json.load(f)

CLIENT_ID = secrets["clientId"]
CLIENT_SECRET = secrets["secret"]

auth_provider = PlainTextAuthProvider(CLIENT_ID, CLIENT_SECRET)
cluster = Cluster(cloud=cloud_config, auth_provider=auth_provider)
session = cluster.connect()



try:
    query = "drop table click_event"
    session.execute(query)
    print("Table dropped successfully !!")
except Exception as err:
    print("Exception Occured while dropping the table: ",err)

# Command to create a table inside a KEyspace
# It has been executed once so commenting it out
try:
    query = """create table click_event(
                ad_id int,
                user_id text,  
                click_timestamp text,  
                platform text,  
                location text,  
                campaign text,  
                product text,  
                target_start_date text,  
                target_end_date text,  
                age int,  
                gender text,  
                interests list<text>,  
                primary key(ad_id,user_id,click_timestamp)
              )
            """
    session.execute(query)
    print("Table created inside the keyspace")
except Exception as err:
    print("Exception Occured while creating the table : ",err)





